/mnt/nas05/clusterdata01/home2/f.barbisch/rle-assginment/.venv/lib/python3.12/site-packages/tyro/_parsers.py:344: UserWarning: The field `wandb-entity` is annotated with type `<class 'str'>`, but the default value `None` has type `<class 'NoneType'>`. We'll try to handle this gracefully, but it may cause unexpected behavior.
  warnings.warn(message)
/mnt/nas05/clusterdata01/home2/f.barbisch/rle-assginment/.venv/lib/python3.12/site-packages/tyro/_parsers.py:344: UserWarning: The field `eval-checkpoint` is annotated with type `<class 'str'>`, but the default value `None` has type `<class 'NoneType'>`. We'll try to handle this gracefully, but it may cause unexpected behavior.
  warnings.warn(message)
/mnt/nas05/clusterdata01/home2/f.barbisch/rle-assginment/.venv/lib/python3.12/site-packages/tyro/_parsers.py:344: UserWarning: The field `target-kl` is annotated with type `<class 'float'>`, but the default value `None` has type `<class 'NoneType'>`. We'll try to handle this gracefully, but it may cause unexpected behavior.
  warnings.warn(message)
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Currently logged in as: florin-barbisch. Use `wandb login --relogin` to force relogin
wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: Tracking run with wandb version 0.19.1
wandb: Run data is saved locally in /mnt/nas05/clusterdata01/home2/f.barbisch/rle-assginment/wandb/run-20241226_121223-rgjhrns5
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run ALE/SpaceInvaders-v5__iem_ppo_coef_0.00001__1__20241226_121202
wandb: ‚≠êÔ∏è View project at https://wandb.ai/florin-barbisch/cleanRL
wandb: üöÄ View run at https://wandb.ai/florin-barbisch/cleanRL/runs/rgjhrns5
A.L.E: Arcade Learning Environment (version 0.10.1+unknown)
[Powered by Stella]
Traceback (most recent call last):
  File "/mnt/nas05/clusterdata01/home2/f.barbisch/rle-assginment/iem_ppo.py", line 407, in <module>
    state1, state2, steps = state_buffers[env_idx].get_all_pairs()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/nas05/clusterdata01/home2/f.barbisch/rle-assginment/iem_ppo.py", line 213, in get_all_pairs
    state1 = torch.stack([p[0] for p in pairs])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 18.00 MiB. GPU 0 has a total capacity of 19.60 GiB of which 15.62 MiB is free. Process 3291739 has 18.62 GiB memory in use. Including non-PyTorch memory, this process has 972.00 MiB memory in use. Of the allocated memory 691.56 MiB is allocated by PyTorch, and 58.44 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
